---
classes:
  - "transmission"
  - "sabnzb"
  - "sickbeard"
  - "couchpotato"
  - "unrar"
  - "spotweb"
  - "apache2"
  - "mysql::server"
  - "php5"
  - "php5::apache"
  - "php5::mysql"

apt::repos:
  "jcfp":
    enabled: true
    location: "http://ppa.launchpad.net/jcfp/ppa/ubuntu"
    release: "%{::lsbdistcodename}"
    repos: "main"
    include_src: false
    key: "0x98703123E0F52B2BE16D586EF13930B14BB9F05F"
    key_server: "hkp://keyserver.ubuntu.com:11371"
  "multiverse":
    enabled: true
    location: "http://archive.ubuntu.com/ubuntu"
    release: "%{::lsbdistcodename}"
    repos: "multiverse"
    include_src: false

transmission:
  download_dir: "/data/torrents"
  rpc-whitelist-enabled: false
  config_dir: "/var/lib/transmission-daemon/info"

sabnzb::config::run_as_user: "sabnzb"
sabnzb::config::http_port: 9090
sickbeard::config::http_port: 9092
couchpotato::config::http_port: 5050
spotweb::config::spotweb_db_host: "localhost"
spotweb::config::spotweb_db_name: "spotweb"
spotweb::config::spotweb_db_user: "spotweb"
spotweb::config::spotweb_db_pass: "spotweb"
