---
classes:
  - "samba"
  - "unrar"
  - "owncloud"
  - "tftpd"

samba::config::workgroup: "SWC"
samba::config::server_string: "%{::hostname}"
samba::config::shares:
  store:
    comment: "Movies, Music, Etc.."
    path: "/data"
    guest_ok: "no"
    browseable: "yes"
    create_mask: "0664"
    directory_mask: "0775"
    writeable: "yes"
  usb:
    comment: "USB Mount"
    path: "/usb"
    guest_ok: "no"
    browseable: "yes"
    create_mask: "0664"
    directory_mask: "0775"
    writeable: "yes"

apt::repos:
  "multiverse":
    enabled: true
    location: "http://archive.ubuntu.com/ubuntu"
    release: "%{::lsbdistcodename}"
    repos: "multiverse"
    include_src: false

tftpd::tftproot_path: "/data/tftproot"
